name: chat_app_signalr
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  dio: ^5.7.0
  shared_preferences: ^2.3.5
  signalr_netcore: ^1.4.0
  sqflite: ^2.4.1
  path_provider: ^2.1.5
  intl:
  firebase_core: ^3.10.0
  firebase_messaging: ^15.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - images/
